-- letshangg preference catalog
-- Idempotent: safe to run multiple times. Existing activity ids are preserved
-- by upserting on activity_key.

insert into public.preference_options (
  label,
  emoji,
  activity_key,
  category,
  quiz_order,
  energy,
  social_setting,
  physical_exertion,
  novelty,
  setting,
  typical_cost,
  time_needed,
  is_active
) values
  ('Grab coffee', null, 'coffee', 'Relaxed & Intimate', 1, 'Low', '1:1 / Small', 'Low', 'Routine', 'Indoor', '$', 'Quick (<1h)', true),
  ('Get pizza', null, 'pizza', 'Relaxed & Intimate', 2, 'Low', 'Small group', 'Low', 'Routine', 'Indoor', '$', 'Quick-1h', true),
  ('Watch a movie', null, 'movie', 'Relaxed & Intimate', 3, 'Low', '1:1 / Small', 'Low', 'Routine', 'Indoor', '$$', 'Half-event', true),
  ('Grab drinks', null, 'drinks', 'Social & Energetic', 4, 'Medium', 'Small / Crowd', 'Low', 'Moderate', 'Indoor', '$$', 'Half-event', true),
  ('Go to a house party', null, 'house_party', 'Social & Energetic', 5, 'High', 'Crowd', 'Low', 'Moderate', 'Indoor', '$', 'Full event', true),
  ('Go dancing / night out', null, 'dancing', 'Social & Energetic', 6, 'High', 'Crowd', 'Medium', 'Moderate', 'Indoor', '$$', 'Full event', true),
  ('Take a workout class', null, 'workout', 'Active & Sporty', 7, 'Medium', 'Small / Crowd', 'High', 'Moderate', 'Indoor', '$$', '1h', true),
  ('Bike ride', null, 'bike', 'Active & Sporty', 8, 'Medium', '1:1 / Small', 'High', 'Moderate', 'Outdoor', '$', 'Half-day', true),
  ('Play a pickup sport', null, 'pickup_sport', 'Active & Sporty', 9, 'High', 'Small / Crowd', 'High', 'Moderate', 'Either', '$', 'Half-day', true),
  ('Go rock climbing', null, 'rock_climbing', 'Active & Sporty', 10, 'High', '1:1 / Small', 'High', 'Novel', 'Either', '$$', 'Half-day', true),
  ('Go for a hike', null, 'hike', 'Outdoorsy & Nature', 11, 'Medium', '1:1 / Small', 'High', 'Moderate', 'Outdoor', '$', 'Half-day', true),
  ('Hang at the park', null, 'park', 'Outdoorsy & Nature', 12, 'Low', 'Small group', 'Low', 'Routine', 'Outdoor', '$', 'Half-day', true),
  ('Sunset walk', null, 'sunset_walk', 'Outdoorsy & Nature', 13, 'Low', '1:1', 'Low', 'Routine', 'Outdoor', '$', 'Quick-1h', true),
  ('Beach / waterfront day', null, 'beach', 'Outdoorsy & Nature', 14, 'Medium', 'Small group', 'Medium', 'Moderate', 'Outdoor', '$', 'Full day', true),
  ('Catch a live show', null, 'show', 'Cultural & Intellectual', 15, 'High', 'Crowd', 'Low', 'Moderate', 'Either', '$$$', 'Full event', true),
  ('Visit a museum', null, 'museum', 'Cultural & Intellectual', 16, 'Low', '1:1 / Small', 'Low', 'Moderate', 'Indoor', '$$', 'Half-day', true),
  ('Bookstore browse', null, 'bookstore', 'Cultural & Intellectual', 17, 'Low', '1:1 / Small', 'Low', 'Routine', 'Indoor', '$', 'Quick-1h', true),
  ('See theater / comedy', null, 'theater_comedy', 'Cultural & Intellectual', 18, 'Medium', 'Crowd', 'Low', 'Moderate', 'Indoor', '$$$', 'Full event', true),
  ('Cook a meal together', null, 'cooking', 'Creative & Hands-On', 19, 'Medium', '1:1 / Small', 'Medium', 'Moderate', 'Indoor', '$', 'Half-event', true),
  ('Take an art / pottery class', null, 'pottery_class', 'Creative & Hands-On', 20, 'Medium', 'Small group', 'Medium', 'Novel', 'Indoor', '$$', 'Half-event', true),
  ('Go thrifting', null, 'thrift', 'Creative & Hands-On', 21, 'Low', '1:1 / Small', 'Low', 'Moderate', 'Indoor', '$', 'Half-day', true),
  ('Go bowling', null, 'bowling', 'Playful & Competitive', 22, 'Medium', 'Small group', 'Medium', 'Moderate', 'Indoor', '$$', 'Half-event', true),
  ('Game night', null, 'game_night', 'Playful & Competitive', 23, 'Medium', 'Small group', 'Low', 'Moderate', 'Indoor', '$', 'Half-event', true),
  ('Arcade / mini-golf', null, 'arcade_mini_golf', 'Playful & Competitive', 24, 'Medium', 'Small group', 'Medium', 'Moderate', 'Either', '$$', 'Half-event', true),
  ('Ice cream run', null, 'ice_cream', 'Indulgent & Sensory', 25, 'Low', '1:1 / Small', 'Low', 'Routine', 'Either', '$', 'Quick (<1h)', true),
  ('Try a new restaurant', null, 'restaurant', 'Indulgent & Sensory', 26, 'Medium', 'Small group', 'Low', 'Novel', 'Indoor', '$$', 'Half-event', true),
  ('Spa / self-care day', null, 'self_care', 'Indulgent & Sensory', 27, 'Low', '1:1', 'Low', 'Moderate', 'Indoor', '$$$', 'Half-day', true),
  ('Day trip / road trip', null, 'day_trip', 'Adventurous & Novel', 28, 'Medium', 'Small group', 'Medium', 'Novel', 'Outdoor', '$$', 'Full day', true),
  ('Escape room', null, 'escape_room', 'Adventurous & Novel', 29, 'High', 'Small group', 'Low', 'Novel', 'Indoor', '$$', '1h', true),
  ('Festival / street fair', null, 'festival', 'Adventurous & Novel', 30, 'High', 'Crowd', 'Medium', 'Novel', 'Outdoor', '$$', 'Full day', true)
on conflict (activity_key) do update set
  label = excluded.label,
  emoji = excluded.emoji,
  category = excluded.category,
  quiz_order = excluded.quiz_order,
  energy = excluded.energy,
  social_setting = excluded.social_setting,
  physical_exertion = excluded.physical_exertion,
  novelty = excluded.novelty,
  setting = excluded.setting,
  typical_cost = excluded.typical_cost,
  time_needed = excluded.time_needed,
  is_active = excluded.is_active;
